### PR TITLE
Hamideh

### PR DESCRIPTION
**Pull request by hamidehAziz**
I modified my user story. please review this.

### CODE REVIEW

**Comment by Buildblock** [comment]
You should assign people to review your work. They can look at it and approve the pull request.

**Comment by hamidehAziz** [comment]
Ok, I assign @miramarhaba  and @AhmadBiz. please review my user story.

**Comment by Buildblock** [comment]
I mean using the Git Hub. Top left, Reviewer section. Click on the cog and assign two people.

**Comment by peters84** [comment]
line 31 is my story
my 2 points are requirements. Should be in the user story section? - @hamidehAziz

You may be right according to this. The link below. I got confused bevause of the order the TA asked for functional reqs and then create user atories based on that. Either way, the last word goes to your assigned reviewers.
https://blog.testlodge.com/user-story-vs-requirements/
As a <type of user>, I want <some desired outcome> so that <some reason>.

**Comment by hamidehAziz** [comment]
I will remove it.

**Pull request merged**
